--[[
	Карта определяет контексты для ивентов по форме
	
	string: string (literal)
]]

local map = require('./')
local contextMap = table.freeze({
	--AbilitySlot0 = nil;
	--AbilitySlot1 = nil;
	--AbilitySlot2 = nil;
	--AbilitySlot3 = nil;
	--AbilitySlot4 = nil;
	--AbilitySlot5 = nil;
	
	--MovementForward = nil;
	--MovementBackward = nil;
	--MovementLeft = nil;
	--MovementRight = nil;
	--MovementJump = nil;
	--MovementShift = nil;
	
	--
})

return contextMap