--[[
	Карта определяет контексты для ивентов по форме
	
	string: string (literal)
]]

local contextMap = table.freeze({
	AbilitySlot0 = 'AbilitySlot0' :: 'AbilitySlot0';
	--AbilitySlot1 = 'AbilitySlot1' :: 'AbilitySlot1';
	--AbilitySlot2 = 'AbilitySlot2' :: 'AbilitySlot2';
	--AbilitySlot3 = 'AbilitySlot3' :: 'AbilitySlot3';
	--AbilitySlot4 = 'AbilitySlot4' :: 'AbilitySlot4';
	--AbilitySlot5 = 'AbilitySlot5' :: 'AbilitySlot5';;
	
	--MovementForward = 'MovementForward' :: 'MovementForward';;
	--MovementBackward = 'MovementBackward' :: 'MovementBackward';;;
	--MovementLeft = 'MovementLeft' :: 'MovementLeft';;
	--MovementRight = 'MovementRight' :: 'MovementRight';;
	--MovementJump = 'MovementJump' :: 'MovementJump';;;
	--MovementShift = 'MovementShift' :: 'MovementShift';;;
	
	--RadialMessage
})

return contextMap